IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'FILMS') AND type in (N'U'))
    CREATE TABLE FILMS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR_IGNORECASE(100) NOT NULL,
	DESCRIPTION VARCHAR_IGNORECASE(200) NOT NULL,
	RELEASEDATE DATE NOT NULL,
	DURATION INTEGER NOT NULL,
	RATE INTEGER,
	LIKECOUNT INTEGER,
	AGERATING VARCHAR_IGNORECASE(5) NOT NULL,
	GENRE INTEGER NOT NULL,
	LIKEUSERID VARCHAR_IGNORECASE,
	CONSTRAINT FILMS_PK PRIMARY KEY (ID)
    );
CREATE UNIQUE INDEX PRIMARY_KEY_88 ON FILMS (ID);
);

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'USERS') AND type in (N'U'))
    CREATE TABLE USERS (
        ID INTEGER NOT NULL AUTO_INCREMENT,
        EMAIL VARCHAR_IGNORECASE(40) NOT NULL,
        LOGIN VARCHAR_IGNORECASE(20) NOT NULL,
        NAME INTEGER,
        BIRTHDAY DATE NOT NULL,
        COLUMN1 JSON,
        CONSTRAINT USERS_PK PRIMARY KEY (ID),
        CONSTRAINT USERS_UNIQUE UNIQUE (EMAIL),
        CONSTRAINT USERS_UNIQUE_1 UNIQUE (LOGIN)
    );
    CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PUBLIC.USERS (ID);
    CREATE UNIQUE INDEX USERS_UNIQUE_1_INDEX_4 ON PUBLIC.USERS (LOGIN);
    CREATE UNIQUE INDEX USERS_UNIQUE_INDEX_4 ON PUBLIC.USERS (EMAIL);
CREATE UNIQUE INDEX PRIMARY_KEY_88 ON FILMS (ID);
);

